### PR TITLE
lang: Ukrainian translation

### PR DESCRIPTION
**Pull request by CakesTwix**

### CODE REVIEW

**Comment by CakesTwix** [comment]
BTW, I have a question. Why didn't you open the source code for the Sortable Storage mod?
I use my Weblate instance for translation and I find it more convenient to have your repository to easily recognize changes.

**Comment by SpearAndFang** [comment]
Oops sorry it is here now
https://github.com/SpearAndFang/sortablestorage

FYI: For some reason, Wild Farming has two language files - there is a second one here with some things...

https://github.com/SpearAndFang/wildfarmingrevival/tree/main/WildFarmingRevival/assets/game/lang

**Comment by CakesTwix** [comment]
Thank you for providing the source code.
Don't take PR yet, I'll update them as well

**Comment by CakesTwix** [comment]
https://github.com/SpearAndFang/sortablestorage/blob/main/assets/sortablestorage/lang/en.json#L31C86-L31C87
For some reason that comma gets in the way. If possible, could you remove it? They are inherent in other languages as well.

**Comment by SpearAndFang** [comment]
I have done it

**Comment by SpearAndFang** [comment]
thanks again!

**Comment by CakesTwix** [comment]
btw, translation of the Primitive Survival mod is [80% complete ](https://weblate.cakestwix.com/projects/opensource/primitive-survival/uk/)

**Comment by SpearAndFang** [comment]
Ha!  That is a LOT of work.

**Pull request merged**
